/**
 * Verilator C++ Testbench Wrapper
 * SuperInstance.AI Mask-Locked Inference Chip
 *
 * This provides a minimal C++ wrapper for fast cycle-accurate simulation.
 * Compile with: make verilator-build
 * Run with: ./Vtop_module
 *
 * Author: VP Manufacturing, SuperInstance.AI
 */

#include <verilated.h>
#include <verilated_vcd_c.h>
#include <iostream>
#include <fstream>
#include <memory>
#include <chrono>
#include <iomanip>

// Generated by Verilator from RTL
#include "Vsuperinstance_inference_engine.h"
#if VERILATOR_VERSION_INTEGER >= 5000000
#include "Vsuperinstance_inference_engine___024root.h"
#endif

//------------------------------------------------------------------------------
// Configuration
//------------------------------------------------------------------------------

const uint64_t MAX_SIM_TIME = 100'000'000;  // 100ms simulation
const uint64_t CLK_PERIOD = 10;             // 10ns = 100MHz
const bool ENABLE_TRACING = true;           // Generate VCD waveforms

//------------------------------------------------------------------------------
// Test Patterns
//------------------------------------------------------------------------------

// Ternary weight patterns for testing
const int TERNARY_WEIGHTS[] = {0, 1, -1, 0, -1, 1, 0, 0, -1, 1};

// Activation test patterns
const uint8_t ACTIVATION_PATTERNS[] = {
    0, 1, 50, 100, 127, 128, 200, 255, 
    64, 192, 32, 224, 16, 240, 8, 248
};

//------------------------------------------------------------------------------
// Performance Monitoring
//------------------------------------------------------------------------------

struct PerformanceCounters {
    uint64_t cycles = 0;
    uint64_t tokens_generated = 0;
    uint64_t operations_completed = 0;
    
    void reset() {
        cycles = 0;
        tokens_generated = 0;
        operations_completed = 0;
    }
    
    void print_summary() const {
        double tokens_per_second = (cycles > 0) 
            ? (double)tokens_generated * 1e9 / (cycles * CLK_PERIOD) 
            : 0;
        double ops_per_second = (cycles > 0) 
            ? (double)operations_completed * 1e9 / (cycles * CLK_PERIOD) 
            : 0;
        
        std::cout << "\n========================================" << std::endl;
        std::cout << "    PERFORMANCE SUMMARY" << std::endl;
        std::cout << "========================================" << std::endl;
        std::cout << "  Total Cycles:      " << std::setw(12) << cycles << std::endl;
        std::cout << "  Tokens Generated:  " << std::setw(12) << tokens_generated << std::endl;
        std::cout << "  Operations:        " << std::setw(12) << operations_completed << std::endl;
        std::cout << "  Simulation Time:   " << std::setw(12) << (cycles * CLK_PERIOD) / 1e6 << " µs" << std::endl;
        std::cout << "  --------------------------------------" << std::endl;
        std::cout << "  Tokens/Second:     " << std::setw(12) << std::fixed << std::setprecision(1) << tokens_per_second << std::endl;
        std::cout << "  MOPS:              " << std::setw(12) << std::fixed << std::setprecision(2) << ops_per_second / 1e6 << std::endl;
        std::cout << "========================================\n" << std::endl;
    }
};

//------------------------------------------------------------------------------
// Main Testbench
//------------------------------------------------------------------------------

int main(int argc, char** argv) {
    std::cout << "\n";
    std::cout << "╔══════════════════════════════════════════════════════════════════════════╗\n";
    std::cout << "║       SuperInstance.AI Mask-Locked Inference Chip Simulator              ║\n";
    std::cout << "║                     Verilator C++ Testbench v1.0                         ║\n";
    std::cout << "╚══════════════════════════════════════════════════════════════════════════╝\n\n";

    // Initialize Verilator
    Verilated::traceEverOn(ENABLE_TRACING);
    Verilated::commandArgs(argc, argv);
    
    // Create DUT instance
    auto dut = std::make_unique<Vsuperinstance_inference_engine>();
    
    // Create trace file
    VerilatedVcdC* trace = nullptr;
    if (ENABLE_TRACING) {
        trace = new VerilatedVcdC;
        dut->trace(trace, 99);
        trace->open("waves/superinstance.vcd");
        std::cout << "[INFO] VCD tracing enabled: waves/superinstance.vcd\n" << std::endl;
    }
    
    // Performance counters
    PerformanceCounters counters;
    
    // Test state
    uint64_t sim_time = 0;
    bool test_complete = false;
    int test_phase = 0;
    uint64_t phase_start_cycle = 0;
    
    //--------------------------------------------------------------------------
    // Test Sequence
    //--------------------------------------------------------------------------
    
    std::cout << "[TEST] Starting simulation...\n" << std::endl;
    std::cout << "  Phase 1: Reset sequence" << std::endl;
    
    // Reset sequence
    dut->rst_n = 0;
    dut->clk = 0;
    
    for (int i = 0; i < 10; i++) {
        dut->clk = !dut->clk;
        dut->eval();
        if (trace) trace->dump(sim_time);
        sim_time += CLK_PERIOD / 2;
    }
    
    dut->rst_n = 1;
    std::cout << "  Phase 2: Idle state verification" << std::endl;
    
    // Main simulation loop
    while (sim_time < MAX_SIM_TIME * CLK_PERIOD && !test_complete) {
        
        // Toggle clock
        dut->clk = !dut->clk;
        
        // Evaluate on rising edge
        if (dut->clk) {
            counters.cycles++;
            
            // Run test phases
            switch (test_phase) {
                case 0:  // Idle state
                    if (counters.cycles == 100) {
                        std::cout << "  Phase 3: Starting inference" << std::endl;
                        dut->start_inference = 1;
                        phase_start_cycle = counters.cycles;
                        test_phase = 1;
                    }
                    break;
                    
                case 1:  // Start inference
                    dut->start_inference = 0;
                    if (dut->busy) {
                        std::cout << "  Phase 4: Inference running..." << std::endl;
                        test_phase = 2;
                    }
                    break;
                    
                case 2:  // Running inference
                    if (dut->token_valid) {
                        counters.tokens_generated++;
                        if (counters.tokens_generated % 10 == 0) {
                            std::cout << "  Tokens: " << counters.tokens_generated << std::endl;
                        }
                    }
                    if (dut->inference_done) {
                        test_phase = 3;
                    }
                    break;
                    
                case 3:  // Complete
                    std::cout << "\n[TEST] Inference complete!" << std::endl;
                    test_complete = true;
                    break;
            }
            
            // Periodic status
            if (counters.cycles % 1'000'000 == 0) {
                std::cout << "  Cycle: " << counters.cycles / 1'000'000 << "M" << std::endl;
            }
        }
        
        // Evaluate design
        dut->eval();
        
        // Dump trace
        if (trace) trace->dump(sim_time);
        sim_time += CLK_PERIOD / 2;
    }
    
    //--------------------------------------------------------------------------
    // Final Report
    //--------------------------------------------------------------------------
    
    if (test_complete) {
        std::cout << "\n[SUCCESS] Test completed successfully!" << std::endl;
    } else {
        std::cout << "\n[TIMEOUT] Simulation reached maximum time." << std::endl;
    }
    
    counters.print_summary();
    
    // Cleanup
    if (trace) {
        trace->close();
        delete trace;
    }
    
    dut->final();
    
    return test_complete ? 0 : 1;
}
