"""
SuperInstance SDK Model Module

Model loading, inference, and generation configuration.
"""

import time
import random
import hashlib
from dataclasses import dataclass, field
from typing import List, Optional, Iterator, Callable, Dict, Any, TYPE_CHECKING

if TYPE_CHECKING:
    from superinstance.device import Device

from superinstance.exceptions import (
    GenerationError,
    ContextLengthExceededError,
    InvalidMessageFormatError,
)


@dataclass
class ContextUsage:
    """Context usage information."""

    used_tokens: int
    max_tokens: int

    @property
    def available_tokens(self) -> int:
        """Number of tokens still available."""
        return self.max_tokens - self.used_tokens

    @property
    def utilization(self) -> float:
        """Context utilization as a fraction (0.0 - 1.0)."""
        return self.used_tokens / self.max_tokens if self.max_tokens > 0 else 0.0


@dataclass
class GenerationConfig:
    """
    Generation parameters for text generation.

    Controls sampling behavior, stopping conditions, and
    output formatting for model.generate() and related methods.
    """

    max_tokens: int = 256
    temperature: float = 0.7
    top_p: float = 0.9
    top_k: int = 40
    stop_sequences: Optional[List[str]] = None
    stop_tokens: Optional[List[int]] = None
    seed: Optional[int] = None
    repetition_penalty: float = 1.0
    frequency_penalty: float = 0.0
    presence_penalty: float = 0.0
    length_penalty: float = 1.0
    echo: bool = False
    logprobs: Optional[int] = None

    def __post_init__(self):
        """Validate configuration parameters."""
        if self.max_tokens < 1:
            raise ValueError("max_tokens must be >= 1")
        if self.temperature < 0 or self.temperature > 2.0:
            raise ValueError("temperature must be between 0.0 and 2.0")
        if self.top_p < 0 or self.top_p > 1.0:
            raise ValueError("top_p must be between 0.0 and 1.0")
        if self.top_k < 0:
            raise ValueError("top_k must be >= 0")


@dataclass
class GenerationResult:
    """
    Result of text generation.

    Contains the generated text and performance metrics.
    """

    text: str
    tokens: List[int]
    prompt_tokens: int
    generated_tokens: int
    tokens_per_second: float
    first_token_latency_ms: float
    total_time_ms: float
    finish_reason: str
    logprobs: Optional[List[dict]] = None
    energy_millijoules: Optional[float] = None
    model_name: Optional[str] = None

    def __len__(self) -> int:
        """Number of generated tokens."""
        return self.generated_tokens

    def __str__(self) -> str:
        """The generated text."""
        return self.text

    def to_dict(self) -> dict:
        """Convert to dictionary."""
        return {
            "text": self.text,
            "tokens": self.tokens,
            "prompt_tokens": self.prompt_tokens,
            "generated_tokens": self.generated_tokens,
            "tokens_per_second": self.tokens_per_second,
            "first_token_latency_ms": self.first_token_latency_ms,
            "total_time_ms": self.total_time_ms,
            "finish_reason": self.finish_reason,
            "logprobs": self.logprobs,
            "energy_millijoules": self.energy_millijoules,
            "model_name": self.model_name,
        }

    def to_json(self) -> str:
        """Convert to JSON string."""
        import json
        return json.dumps(self.to_dict(), indent=2)


class Model:
    """
    Loaded language model interface.

    Provides methods for text generation, tokenization, and
    model introspection. Models are loaded from cartridges
    or model files via the Device class.
    """

    # Simulated model responses for demo mode
    _SIMULATED_RESPONSES = [
        "I'm a language model running on dedicated hardware. How can I help you today?",
        "This is a simulated response from the SuperInstance SDK. In production, this would be generated by the actual model on the device.",
        "The quick brown fox jumps over the lazy dog. This sentence contains all the letters of the English alphabet.",
        "Hello! I'm running entirely on the SuperInstance mask-locked inference chip, processing everything locally without cloud connectivity.",
        "I can help you with various tasks like answering questions, writing text, or having a conversation - all running at 25-35 tokens per second on just 3 watts of power.",
    ]

    def __init__(
        self,
        device: "Device",
        model_path: Optional[str] = None,
        simulate: bool = False
    ):
        """
        Initialize a Model instance.

        This is typically called via Device.load_cartridge() or Device.load_model().

        Args:
            device: The Device instance this model is loaded on
            model_path: Optional path to a custom model file
            simulate: Whether to run in simulation mode
        """
        self._device = device
        self._model_path = model_path
        self._simulate = simulate
        self._context: List[int] = []
        self._system_prompt: Optional[str] = None

        # Model metadata (would be read from cartridge/model file in production)
        self._name = "bitnet-2b-chat"
        self._version = "1.0.0"
        self._context_length = 4096
        self._vocab_size = 32000
        self._parameters = 2_000_000_000
        self._quantization = "ternary"

        if model_path:
            # Would load model metadata from file
            self._name = os.path.basename(model_path).replace(".simod", "")

    @property
    def name(self) -> str:
        """Model name from cartridge metadata."""
        return self._name

    @property
    def version(self) -> str:
        """Model version string."""
        return self._version

    @property
    def context_length(self) -> int:
        """Maximum context length in tokens."""
        return self._context_length

    @property
    def vocab_size(self) -> int:
        """Vocabulary size."""
        return self._vocab_size

    @property
    def parameters(self) -> int:
        """Total parameter count."""
        return self._parameters

    @property
    def quantization(self) -> str:
        """Quantization scheme: 'ternary', 'c4_complex', 'int4'."""
        return self._quantization

    def generate(
        self,
        prompt: str,
        config: Optional[GenerationConfig] = None
    ) -> GenerationResult:
        """
        Generate complete response for prompt.

        Args:
            prompt: Input text prompt
            config: Generation parameters (optional)

        Returns:
            GenerationResult with output text and metadata

        Raises:
            ContextLengthExceededError: Prompt exceeds context length
            GenerationError: Generation failed
        """
        if config is None:
            config = GenerationConfig()

        # Tokenize prompt
        prompt_tokens = self.tokenize(prompt)
        if len(prompt_tokens) > self._context_length:
            raise ContextLengthExceededError(len(prompt_tokens), self._context_length)

        # Generate
        start_time = time.time()
        first_token_time = None

        if self._simulate:
            text, tokens = self._simulate_generation(prompt, config)
        else:
            # Real generation would happen here
            raise GenerationError(
                "No physical device available. Use simulation mode."
            )

        end_time = time.time()
        total_time_ms = (end_time - start_time) * 1000

        # Calculate metrics
        generated_tokens = len(tokens)
        tokens_per_second = generated_tokens / ((end_time - start_time) or 0.001)
        first_token_latency_ms = 50.0 + random.uniform(10, 40)  # Simulated

        return GenerationResult(
            text=text,
            tokens=tokens,
            prompt_tokens=len(prompt_tokens),
            generated_tokens=generated_tokens,
            tokens_per_second=tokens_per_second,
            first_token_latency_ms=first_token_latency_ms,
            total_time_ms=total_time_ms,
            finish_reason="length" if len(tokens) >= config.max_tokens else "stop",
            energy_millijoules=generated_tokens * 0.12,  # ~0.12 mJ per token at 3W
            model_name=self._name,
        )

    def generate_stream(
        self,
        prompt: str,
        config: Optional[GenerationConfig] = None,
        callback: Optional[Callable[[str], None]] = None
    ) -> Iterator[str]:
        """
        Stream tokens as they are generated.

        This method provides real-time output, yielding each token
        as it is produced by the model.

        Args:
            prompt: Input text prompt
            config: Generation parameters (optional)
            callback: Optional callback called with each token

        Yields:
            Individual tokens as strings
        """
        if config is None:
            config = GenerationConfig()

        # Generate full response first (in simulation)
        result = self.generate(prompt, config)
        text = result.text

        # Stream word by word for simulation
        words = text.split()
        for i, word in enumerate(words):
            # Simulate token generation delay
            time.sleep(0.03 + random.uniform(0, 0.02))  # ~25-35 tok/s

            token = word if i == 0 else " " + word
            if callback:
                callback(token)
            yield token

    def chat(
        self,
        messages: List[dict],
        config: Optional[GenerationConfig] = None
    ) -> GenerationResult:
        """
        Chat-style generation with message history.

        Supports multi-turn conversations with role-based messages.
        Messages should follow the OpenAI chat format:

        [
            {"role": "system", "content": "You are helpful."},
            {"role": "user", "content": "Hello!"},
            {"role": "assistant", "content": "Hi there!"},
            {"role": "user", "content": "How are you?"}
        ]

        Args:
            messages: List of message dictionaries with 'role' and 'content'
            config: Generation parameters (optional)

        Returns:
            GenerationResult with assistant's response

        Raises:
            InvalidMessageFormatError: Message format invalid
        """
        # Validate message format
        for msg in messages:
            if not isinstance(msg, dict):
                raise InvalidMessageFormatError(
                    "Each message must be a dictionary."
                )
            if "role" not in msg or "content" not in msg:
                raise InvalidMessageFormatError(
                    "Each message must have 'role' and 'content' keys."
                )
            if msg["role"] not in ("system", "user", "assistant"):
                raise InvalidMessageFormatError(
                    f"Invalid role: {msg['role']}. Must be 'system', 'user', or 'assistant'."
                )

        # Format as prompt
        prompt_parts = []
        for msg in messages:
            role = msg["role"]
            content = msg["content"]
            if role == "system":
                prompt_parts.append(f"System: {content}")
            elif role == "user":
                prompt_parts.append(f"User: {content}")
            elif role == "assistant":
                prompt_parts.append(f"Assistant: {content}")

        prompt_parts.append("Assistant:")
        prompt = "\n".join(prompt_parts)

        return self.generate(prompt, config)

    def chat_stream(
        self,
        messages: List[dict],
        config: Optional[GenerationConfig] = None
    ) -> Iterator[str]:
        """
        Streaming chat generation.

        Combines chat formatting with streaming output.

        Args:
            messages: List of message dictionaries
            config: Generation parameters (optional)

        Yields:
            Individual tokens as strings
        """
        result = self.chat(messages, config)
        text = result.text

        words = text.split()
        for i, word in enumerate(words):
            time.sleep(0.03 + random.uniform(0, 0.02))
            yield word if i == 0 else " " + word

    def tokenize(self, text: str) -> List[int]:
        """
        Convert text to token IDs.

        In production, this uses the model's actual tokenizer.
        For simulation, we use a simple word-based approximation.

        Args:
            text: Input text string

        Returns:
            List of integer token IDs
        """
        if self._simulate:
            # Simple simulation: hash each word
            tokens = []
            words = text.split()
            for word in words:
                # Use hash to get a pseudo-random but consistent token ID
                h = int(hashlib.md5(word.encode()).hexdigest()[:8], 16)
                tokens.append(h % self._vocab_size)
            return tokens
        else:
            raise NotImplementedError(
                "Tokenization requires physical device or tokenizer model."
            )

    def detokenize(self, tokens: List[int]) -> str:
        """
        Convert token IDs to text.

        In production, this uses the model's actual tokenizer.
        For simulation, we generate placeholder text.

        Args:
            tokens: List of integer token IDs

        Returns:
            Decoded text string
        """
        if self._simulate:
            # Simple simulation: generate placeholder words
            words = []
            for i, token_id in enumerate(tokens):
                # Generate pseudo-random but reproducible words
                random.seed(token_id)
                word_len = random.randint(3, 8)
                word = ''.join(chr(97 + random.randint(0, 25)) for _ in range(word_len))
                words.append(word)
            return " ".join(words)
        else:
            raise NotImplementedError(
                "Detokenization requires physical device or tokenizer model."
            )

    def count_tokens(self, text: str) -> int:
        """
        Count number of tokens in text.

        Args:
            text: Input text string

        Returns:
            Number of tokens
        """
        return len(self.tokenize(text))

    def set_system_prompt(self, prompt: str) -> None:
        """
        Set persistent system prompt.

        The system prompt is prepended to all subsequent generations
        until cleared or changed.

        Args:
            prompt: System prompt text
        """
        self._system_prompt = prompt

    def clear_context(self) -> None:
        """Clear all context and KV cache."""
        self._context = []
        self._system_prompt = None

    def get_context_usage(self) -> ContextUsage:
        """
        Get current context usage.

        Returns:
            ContextUsage with token counts and utilization
        """
        return ContextUsage(
            used_tokens=len(self._context),
            max_tokens=self._context_length,
        )

    def _simulate_generation(
        self,
        prompt: str,
        config: GenerationConfig
    ) -> tuple:
        """
        Simulate text generation for demo mode.

        In production, this would run inference on the device.

        Args:
            prompt: Input prompt
            config: Generation configuration

        Returns:
            Tuple of (generated_text, token_ids)
        """
        # Use seed for reproducibility if provided
        if config.seed is not None:
            random.seed(config.seed)

        # Select a base response
        base_response = random.choice(self._SIMULATED_RESPONSES)

        # Customize based on prompt
        prompt_lower = prompt.lower()

        if "hello" in prompt_lower or "hi" in prompt_lower:
            response = "Hello! I'm running on SuperInstance hardware. How can I help you today?"
        elif "what" in prompt_lower and "you" in prompt_lower:
            response = "I'm a language model running on dedicated mask-locked inference hardware. I can help with text generation, answering questions, and having conversations - all locally without internet connectivity."
        elif "story" in prompt_lower:
            response = "Once upon a time, in a world where AI ran on dedicated hardware, a small chip named SuperInstance dreamed of processing tokens efficiently. At just 3 watts, it could generate 25-35 tokens per second, making it the most efficient storyteller in the land."
        elif "code" in prompt_lower or "python" in prompt_lower:
            response = "Here's a simple Python example:\n\n```python\nfrom superinstance import Device\n\ndevice = Device()\nmodel = device.load_cartridge()\nresult = model.generate('Write hello world')\nprint(result.text)\n```\n\nThis code connects to the device and generates text locally."
        elif "help" in prompt_lower:
            response = "I can help you with:\n- Text generation and creative writing\n- Answering questions\n- Code examples and explanations\n- Conversation and chat\n- Summarization\n\nAll processing happens locally on the SuperInstance chip - no cloud required!"
        else:
            # Extend base response based on max_tokens
            response = base_response

            # Pad response if needed for longer generations
            if config.max_tokens > 100:
                extras = [
                    " I can process your requests entirely locally.",
                    " This means your data stays private.",
                    " No internet connection required.",
                    " Running at 25-35 tokens per second.",
                ]
                while len(response.split()) < config.max_tokens:
                    response += random.choice(extras)

        # Truncate if needed
        words = response.split()
        if len(words) > config.max_tokens:
            words = words[:config.max_tokens]
            response = " ".join(words)

        # Generate token IDs
        tokens = [random.randint(0, self._vocab_size - 1) for _ in words]

        return response, tokens

    def _reset(self) -> None:
        """Reset model state."""
        self._context = []
        self._system_prompt = None

    def __repr__(self) -> str:
        """String representation."""
        return f"<Model name={self._name} context_length={self._context_length}>"


# Import os for path operations
import os
